#include <time.h>
#ifndef WORK_H
#define WORK_H

#define EVIL_LAB_ASSISTANT 1
#define OWCA_HIRING_MANAGER 2
#define CIKAPUNDUNGINATOR_CARETAKER 3
#define MEWING_SPECIALIST 4
#define INATOR_CONNOISSEUR 5

#define EVIL_LAB_ASSISTANT_SALARY 100
#define OWCA_HIRING_MANAGER_SALARY 4200
#define CIKAPUNDUNGINATOR_CARETAKER_SALARY 7000
#define MEWING_SPECIALIST_SALARY 10000
#define INATOR_CONNOISSEUR_SALARY 997

#define EVIL_LAB_ASSISTANT_DURATION 14
#define OWCA_HIRING_MANAGER_DURATION 21
#define CIKAPUNDUNGINATOR_CARETAKER_DURATION 30
#define MEWING_SPECIALIST_DURATION 22
#define INATOR_CONNOISSEUR_DURATION 15

typedef struct {
  int job_id;
  int salary;
  int duration;
} Job;

Job get_job(int job_id);

void delay(int sec);

void start_job(int duration, int salary);

#endif
